language: java
jdk:
  - openjdk11
os:
  - linux

sudo: false

before_cache:
  - rm -rf  ${HOME}/.m2/repository/spring/boots/shorten-url/1.0-SNAPSHOT/

cache:
  directories:
    - $HOME/.m2

script:
  - echo "========================== Script Start =========================="
  - java -version
  - mvn clean install
  - mvn test
  - echo 'HOME folder: '${HOME}
  - echo "========================== Script End =========================="

notifications:
  email: false