language: java
version: ~> 1.0
dist: xenial

os:
  - linux

jdk:
  - openjdk11

sudo: false

branches:
  only:
    - master
    - develop

before_cache:
  - rm -rf  ${HOME}/.m2/repository/spring/boots/shorten-url/1.0-SNAPSHOT/

cache:
  directories:
    - ~/.m2

script:
  - echo "========================== Script Start =========================="
  - java -version
  - mvn test
  - mvn clean install -DskipTests=true
  - echo "========================== Script End =========================="

notifications:
  email: false