language: java

jdk:
  - openjdk11

os:
  - linux

sudo: false

before_cache:
  - rm -rf  ${HOME}/.m2/repository/spring/boots/shorten-url/1.0-SNAPSHOT/

cache:
  directories:
    - $HOME/.m2

script:
  - echo "========================== Script Start =========================="
  - java -version
  - mvn test
  - mvn clean install -DskipTests=true
  - echo "========================== Script End =========================="

notifications:
  email: false